name: Testing and Building

on:
  push:
    branches:
      - main
      - release/*
      - github-action/*
  pull_request:
    branches:
      - main

# https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#concurrency
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install invoke==2.2.0 clang-format==18.1.8

      - name: Check formatting
        run: |
          invoke fmt --check --verbose
  
  UnitTest:
    name: UnitTest-${{ matrix.toolchain }}
    runs-on: ${{ matrix.os }}
    needs: Linting
    strategy:
      fail-fast: true
      matrix:
        toolchain:
          - linux-gcc
          - macos-clang
          - windows-msvc

        include:
          - toolchain: linux-gcc
            os: ubuntu-latest
            host: linux
          - toolchain: macos-clang
            os: macos-latest
            host: mac
          - toolchain: windows-msvc
            os: windows-latest
            host: windows
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - uses: jurplel/install-qt-action@v4
        with:
          version: "6.8.0"
          host: ${{ matrix.host }}
      - name: Install dependencies
        if : matrix.host == 'linux'
        run: |
          pip install --user -U gcovr
      - name: Build and Test (Linux)
        if : matrix.host == 'linux'
        run: |
          make clean
          make cov
      - name: Build and Test (Windows, macOS)
        if : matrix.host != 'linux'
        run: |
          make clean
          make test
      - name: Code Coverage Report
        if : matrix.host == 'linux'
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: build/coverage/coverage.cobertura.xml
          badge: true
          fail_below_min: true
          format: markdown
          hide_branch_rate: false
          hide_complexity: true
          indicators: true
          output: both
          thresholds: "7 80"
      - name: Add Coverage PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request' && matrix.host == 'linux'
        with:
          recreate: true
          path: code-coverage-results.md

  Building:
    name: Building-${{ matrix.toolchain }}
    runs-on: ${{ matrix.os }}
    needs: [Linting, UnitTest]
    strategy:
      fail-fast: true
      matrix:
        toolchain:
          - linux-gcc
          - macos-clang
          - windows-msvc

        include:
          - toolchain: linux-gcc
            os: ubuntu-latest
            host: linux
          - toolchain: macos-clang
            os: macos-latest
            host: mac
          - toolchain: windows-msvc
            os: windows-latest
            host: windows

    steps:
      - uses: actions/checkout@v4
      - uses: jurplel/install-qt-action@v4
        with:
          version: "6.8.0"
          host: ${{ matrix.host }}

      - name: Configure
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build on ${{ matrix.toolchain }}
        run: cmake --build build --config Release --parallel