name: Release

on:
  push:
    branches:
      - main
      - release/*

# https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#concurrency
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Release:
    name: Building-${{ matrix.toolchain }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        toolchain:
          - linux-gcc
          - macos-clang
          - windows-msvc

        include:
          - toolchain: linux-gcc
            os: ubuntu-latest
            host: linux
          - toolchain: macos-clang
            os: macos-latest
            host: mac
          - toolchain: windows-msvc
            os: windows-latest
            host: windows

    steps:
      - uses: actions/checkout@v4
      - uses: jurplel/install-qt-action@v4
        with:
          version: "6.8.0"
          host: ${{ matrix.host }}

      - name: Configure
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build on ${{ matrix.toolchain }}
        run: cmake --build build --config Release --parallel

      - run: mkdir -p build/artifacts
      - if: matrix.host == 'linux'
        run: |
          ls -l -R /home/runner/work/Qt-Time-Tracker/Qt/6.8.0/gcc_64/bin
      - if: matrix.host == 'mac'
        run: |
          ls -R /Users/runner/work/Qt-Time-Tracker/Qt/6.8.0/macos/bin
          /Users/runner/work/Qt-Time-Tracker/Qt/6.8.0/macos/bin/macdeployqt build/TimeTracker.app -verbose=2
          codesign --force --deep --sign - build/TimeTracker.app
          mv build/TimeTracker.app build/artifacts
      - if: matrix.host == 'windows'
        run: |
          ls -R D:/a/Qt-Time-Tracker/Qt/6.8.0/msvc2022_64/bin
          D:/a/Qt-Time-Tracker/Qt/6.8.0/msvc2022_64/bin/windeployqt.exe build/Release/TimeTracker.exe -verbose=2
          mv build/Release/TimeTracker.exe build/artifacts

      - uses: actions/upload-artifact@v4
        with:
          name: artifact-${{ matrix.host }}
          path: build/artifacts
